services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TOKEN: TOKEN
    container_name: backend-service
    ports:
      - "8081:8080"

volumes:
  db-anidle:

networks:
  anidle-net:
    name: anidle-net
    driver: bridge
